### ISSUE TITLE
Error in testing this ORM module

### ISSUE THREAD

**Issue by jeffbrown57** [meatballs/anvil-model#16]
**TypeError**: __init__() got an unexpected keyword argument 'cls'

this in the class Relationship

@property
    def **cls**(self):
       return getattr(sys.modules[self.__module__], self.class_name)

**Comment by meatballs** [comment]
For reporting a bug, it's helpful if you could explain exactly how to reproduce the problem.

**Comment by jeffbrown57** [comment]
> For reporting a bug, it's helpful if you could explain exactly how to reproduce the problem.

If you follow the tutorial found at this link:
     https://anvil-orm.readthedocs.io/en/latest/tutorial.html

And perform. the steps involved, you get the error above.

**Comment by meatballs** [comment]
Where exactly in the tutorial does the error occur?

**Comment by jeffbrown57** [comment]
> Where exactly in the tutorial does the error occur?
at:
**Add Some Entries**
Create a new module in the client code section of your app, name it ‘startup’ and set it as the startup module. Delete its content and replace it with:  ( model file created as instructed(

**Launch your app** and stop it again. You should see the results of the print statements in its output console.
 Do this and get this error seen above...

**Comment by meatballs** [comment]
That was a bug in the tutorial. This line:
```
author = Relationship(cls="Author")
```

should instead be:
```
author = Relationship(class_name="Author")
```

I've update readthedocs to show that.

I've also corrected the server module imports so they match the tutorial structure. You should delete the content of your `persistence` and `security` modules and copy them again from the links in the tutorial.

**Comment by jeffbrown57** [comment]
> That was a bug in the tutorial. This line:
> 
> ```
> author = Relationship(cls="Author")
> ```
> 
> should instead be:
> 
> ```
> author = Relationship(class_name="Author")
> ```
> 
> I've update readthedocs to show that.
> 
> I've also corrected the server module imports so they match the tutorial structure. You should delete the content of your `persistence` and `security` modules and copy them again from the links in the tutorial.

Excellent , thank you very much .....

**Comment by jeffbrown57** [comment]
> That was a bug in the tutorial. This line:
> 
> ```
> author = Relationship(cls="Author")
> ```
> 
> should instead be:
> 
> ```
> author = Relationship(class_name="Author")
> ```
> 
> I've update readthedocs to show that.
> 
> I've also corrected the server module imports so they match the tutorial structure. You should delete the content of your `persistence` and `security` modules and copy them again from the links in the tutorial.

After making this change, i was able to. get past the error complaining about cls= , but now
it fails with this error: 
anvil.tables.TableError:` Column 'uid' is a number - cannot set it to a string

at this code:
in orm_server/persistence.py
`row` = table.add_row(uid=uid, **members).   uid is a string here . uid = `uuid4().hex`

i fixed that by doing `uid` = `int(uuid4().hex))`

but that led to more errors  ,  i gave up
