### ISSUE TITLE
Error in testing the ORM module ( follow-on)

### ISSUE THREAD

**Issue by jeffbrown57** [meatballs/anvil-model#17]
After making these changes, i was able to. get past the error complaining about cls= , but now
it fails with this error:

anvil.tables.TableError:` Column 'uid' is a number - cannot set it to a string

in this code:
   in orm_server/persistence.py
`row = table.add_row(uid=uid, **members)`
          ## uid is a string here . uid = uuid4().hex

i fixed that by doing `uid = int(uuid4().hex, 10)`      ## in code a few lines above

but that led to more errors , i gave up ....

**Comment by meatballs** [comment]
That's another bug in the tutorial. The `uid` columns in the data tables should be text columns rather than numbers. (We used to use an integer sequence for the uid but we swapped to a uuid and the tutorial didn't get updated).
